define(["jade"],function(jade){

return function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (user) {
buf.push("<div class=\"profilebar\"><h1 class=\"profile_name\"><i class=\"glyphicon glyphicon-chevron-right\"></i>" + (jade.escape(null == (jade_interp = user.get("name")) ? "" : jade_interp)) + "</h1><img" + (jade.attr("src", "" + (user.get('avatar')) + "", true, false)) + "/><div id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\" class=\"panel-group\"><div class=\"panel panel-default\"><div id=\"profileAccordion\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#profileCollapse\" aria-expanded=\"false\" aria-controls=\"profileCollapse\"><i class=\"glyphicon glyphicon-chevron-right\"></i>プロフィール</a></h4></div><div id=\"profileCollapse\" role=\"tabpanel\" aria-labelledby=\"profileAccordion\" class=\"panel-collapse collapse\"><ul role=\"tablist\" class=\"list-group\"><li class=\"list-group-item\">Archi</li><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li></ul></div></div><div class=\"panel panel-default\"><div id=\"achievementAccordion\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#achivementCollapse\" aria-expanded=\"false\" aria-controls=\"achivementCollapse\" class=\"collapsed\"><i class=\"glyphicon glyphicon-chevron-right\"></i>実績</a></h4></div><div id=\"achivementCollapse\" role=\"tabpanel\" aria-labelledby=\"achievementAccordion\" class=\"panel-collapse collapse\"><ul role=\"tablist\" class=\"list-group\"><a href=\"#allUserAchivement\" aria-controls=\"allUserAchivement\" role=\"tab\" data-toggle=\"tab\"><li class=\"list-group-item\">全て</li></a></ul></div></div><div class=\"panel panel-default\"><div id=\"accountAccordion\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#accountCollapse\" aria-expanded=\"false\" aria-controls=\"accountCollapse\" class=\"collapsed\"><i class=\"glyphicon glyphicon-chevron-right\"></i>各種アカウント</a></h4></div><div id=\"accountCollapse\" role=\"tabpanel\" aria-labelledby=\"accountAccordion\" class=\"panel-collapse collapse\"><ul role=\"\" class=\"list-group\"><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li></ul></div></div></div></div><div class=\"panels\"><h1>hello</h1><div id=\"allUserAchivement\" role=\"tabpanel\" data-js=\"achivementList\" class=\"panelcontent tab-pane fade\"><div class=\"row\"><div class=\"col-xs-12\"><div class=\"title text-center\">実績一覧</div></div></div></div></div>");}.call(this,"user" in locals_for_with?locals_for_with.user:typeof user!=="undefined"?user:undefined));;return buf.join("");
};

});
