define(["jade"],function(jade){

return function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (user) {
buf.push("<div class=\"profilebar\"><h1 class=\"profile_name\"><i class=\"glyphicon glyphicon-chevron-right\"></i>" + (jade.escape(null == (jade_interp = user.get("name")) ? "" : jade_interp)) + "</h1><img" + (jade.attr("src", "" + (user.get('avatar')) + "", true, false)) + "/>\n<div id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\" class=\"panel-group\"><div class=\"panel panel-default\"><div id=\"profileAccordion\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#profileCollapse\" aria-expanded=\"true\" aria-controls=\"profileCollapse\"><i class=\"glyphicon glyphicon-chevron-right\"></i>プロフィール</a></h4></div><div id=\"profileCollapse\" role=\"tabpanel\" aria-labelledby=\"profileAccordion\" class=\"panel-collapse collapse in\"><ul class=\"list-group\"><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li></ul></div></div><div class=\"panel panel-default\"><div id=\"accountAccordion\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#accountCollapse\" aria-expanded=\"false\" aria-controls=\"accountCollapse\" class=\"collapsed\"><i class=\"glyphicon glyphicon-chevron-right\"></i>各種アカウント</a></h4></div><div id=\"accountCollapse\" role=\"tabpanel\" aria-labelledby=\"accountAccordion\" class=\"panel-collapse collapse\"><ul class=\"list-group\"><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li><li class=\"list-group-item\">hoge</li></ul></div></div><div class=\"panel panel-default\"><div id=\"achievementAccordion\" role=\"tab\" class=\"panel-heading\"><h4 class=\"panel-title\"><a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#achivementCollapse\" aria-expanded=\"false\" aria-controls=\"achivementCollapse\" class=\"collapsed\"><i class=\"glyphicon glyphicon-chevron-right\"></i>実績</a></h4></div><div id=\"achivementCollapse\" role=\"tabpanel\" aria-labelledby=\"achievementAccordion\" class=\"panel-collapse collapse\"><ul class=\"list-group\"><li class=\"list-group-item\">全て</li></ul></div></div></div></div><div class=\"profilecontent\"><div id=\"achivementPanel\"><h1>hello!</h1></div></div>");}.call(this,"user" in locals_for_with?locals_for_with.user:typeof user!=="undefined"?user:undefined));;return buf.join("");
};

});
